const RUBBISH = 'zEByyjS2s9iOHqOz';

const EMPTY_PASSWORD = '';
const VALID_PASSWORD = 'secret1234';
const PASSWORD_WITH_SPECIAL_CHARS = '_-/1 8Mwhr4vCAd*#';

module.exports = {
    RUBBISH,
    EMPTY_PASSWORD, VALID_PASSWORD, PASSWORD_WITH_SPECIAL_CHARS,
};